# Generated by Django 2.2 on 2020-02-04 11:24

import comments.models
import comments.validation
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d')),
                ('content', models.CharField(blank=True, max_length=140, validators=[comments.validation.validate_content])),
                ('updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('comments', djongo.models.fields.ArrayModelField(blank=True, model_container=comments.models.comment, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.IntegerField(default=comments.models.comment.ids, unique=True)),
                ('messages', models.CharField(blank=True, max_length=140)),
                ('time', models.DateTimeField(auto_now=True)),
                ('no_of_like', models.IntegerField(blank=True)),
                ('likes', djongo.models.fields.ArrayModelField(blank=True, model_container=comments.models.like, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
